services:

  mysql-primary:
    image: mysql:8.0
    container_name: mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --log-replica-updates=ON
    ports:
      - "3306:3306"

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=2
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --read-only=ON
    ports:
      - "3307:3306"
    depends_on:
      - mysql-primary

  mysql-shard2:
    image: mysql:8.0
    container_name: mysql-shard2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_shard2
    ports:
      - "3308:3306"